export enum AccessCode {
  // 角色管理
  AUTHORITY_ROLE_LOOKUP = "AUTHORITY_ROLE_LOOKUP",
  AUTHORITY_ROLE_CREATE = "AUTHORITY_ROLE_CREATE",
  AUTHORITY_ROLE_UPDATE = "AUTHORITY_ROLE_UPDATE",
  AUTHORITY_ROLE_DELETE = "AUTHORITY_ROLE_DELETE",
  // 用户管理
  AUTHORITY_USER_LOOKUP = "AUTHORITY_USER_LOOKUP",
  AUTHORITY_USER_CREATE = "AUTHORITY_USER_CREATE",
  AUTHORITY_USER_UPDATE = "AUTHORITY_USER_UPDATE",
  AUTHORITY_USER_DELETE = "AUTHORITY_USER_DELETE",

  SYSTEM_PARAMS_LOOKUP = "SYSTEM_PARAMS_LOOKUP",
  OTHER_OTHER_LOOKUP = "OTHER_OTHER_LOOKUP",
  OTHER_OTHER1_OTHER1_LOOKUP = "OTHER_OTHER1_OTHER1_LOOKUP",
}
